apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crontest
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:  
      template:
        spec:
          containers:
            - name: crontest
              image: hub/image
              env:
                - name: MONGODB_PASS
                  value: mongodb
            restartPolicy: OnFailure
